---
title: "General Education Proposal"
author: "Dickinson State University"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: rmarkdown::tufte_handout

---

# Mission Statement

\newthought{In alignment with Dickinson State University's mission}, the General Education program both complements and transcends individual academic emphases. Through the General Education curriculum^[39 TOTAL CREDITS REQUIRED], students demonstrate the following proficiencies: effective communication, citizenship, critical and creative thinking, and integrative learning. In meeting these proficiencies, students mature into independent life-long learners.

--------------------------------

# General Education Learning Outcomes

## Communication^[9 CREDITS REQUIRED]
\newthought{Definition:} Communication is the sharing of ideas through written, oral, and symbolic language. It involves the active expression and reception of ideas through multiple technologies, physical and spoken language, mixed texts, data, and images.
\newthought{Goal Statement:} Students will apply multiple conventions of expression to achieve shared understanding of meaning.

\newthought{Student Outcomes:} 


1. Adapt modes and styles of writing to different purposes, audiences, media, and contexts.
2. Develop effective pre-writing, researching, drafting, revising, proofreading, and editing processes.
3. Utilize writing technologies crucial to performance in today's writing-intensive professions. 
4. Organize and convey a central message via oral communication, using supporting evidence and adapting language and delivery for audience
5. Initiate and negotiate in a collaborative setting by listening to, building upon, verifying, or challenging others' ideas and conclusions

\newpage

\newthought{Required Coursework:}
Students are required to pass nine credits of communication coursework with at least one course from each list in table one. 

------------------------------------------------------------------------------------------------------------
                                                    Outcomes
List Course                     GERTA      Credits   1           2         3        4       5
---- -------------------------- --------- --------- ----------- --------- -------- ------ ------- 
A     ENGL 110:                 ENGL       3          +           +         +       -      -
      *College Composition I*

A     ENGL 111H:                ENGL       3          +           +         +       -      -
      *Honors College*
      *Composition I*

B     ENGL 120:                 ENGL       3          +           +        +        -      -
      *College Composition II*

B     ENGL 121H:                ENGL       3          +           +        +        -      -
      *Honors College*
      *Composition II*

C     COMM 110:                 COMM       3           -           -       -        +      +   
      *Public Speaking*

C     COMM 111H:                COMM       3           -           -       -        +      +   
      *Honors Public*
      *Speaking*
----------------------------------------------------------------------------------------------------------
Table: Communication Courses

---------------------------------------------------

\newpage
## Citizenship^[11 CREDITS REQUIRED]
\newthought{Definition:} Citizenship involves individuals attuned to the multiple perspectives inherent in our socially and culturally diverse world. Citizens are cognizant of their own health and well-being, demonstrate an understanding of the impact one has on the arenas outside of the self, and engage with complex, authentic issues both locally and globally.
\newthought{Goal Statement:} Students will progressively maintain their personal health and well-being and consider diverse social-cultural perspectives as they integrate and evaluate approaches to local and global issues.

\newthought{Student Outcomes:}

1. Identify and incorporate strategies leading to individual health and well-being
2. Predict and analyze the effects that one's decisions have on the well-being of others
3. Integrate political, social, and cultural structures, utilizing multiple viewpoints, to contribute to a community's values and practices
4. Apply technology effectively, safely and ethically in an evolving society

\newpage
\newthought{Required Coursework:}
Students are required to pass eleven credits of citizenship coursework with at least one course from each list in table two. 

------------------------------------------------------------------------------------------------------------
                                                    Outcomes
List Course                   GERTA      Credits   1           2         3        4    
---- ----------------------- --------- --------- ----------- --------- -------- ------ 
A      CSCI 101:                COMPSC      3          +        -         -        +  
      *Introduction to*
      *Computers*

B      COMM 216:                 SS         3          +           +         +    +
      *Intercultural*
      *Communications*

B      GEOG  121:                 SS*      3          ?           ?       ?       ?
      *Physical Geography*

B      GEOG  161:                 SS      3          ?           ?       ?       ?
      *World Regional*
      *Geography*

B      SPAN  101:                 HUM      3          ?           ?       ?       ?
       *First Year*
       *Spanish I*

B      SPAN  102:                 HUM      3          ?           ?       ?       ?
       *First Year*
       *Spanish II*

C      POLS 115:                 SS         3          +           +         +     + 
      *American*
      *Government*

C      PSYC 111:                   SS        3        +            +        +     +
       *Introduction to*
       *Psychology*

C      SOC 110:                  SS         3          -           -         +      +  
      *Introduction to*
      *Sociology*
      
C      SOC  115:                    SS     3          ?           ?       ?       ?
      *Social Problems*

D      HPER 100:                           2          +           +         -        -
       *Concepts of*
       *Health & Wellness*
      
D      NURS 240:                            2          +           +         -        -
       *Fundamentals of*
       *Nutirition*
       
----------------------------------------------------------------------------------------------------------
Table: Citizenship Courses.  

--------------------------------------------

\newpage
## Critical and Creative Thinking^[16 CREDITS REQUIRED]

\newthought{Definition:} Critical and creative thinking are intellectual skills in which knowledge and literacy are used to process information, construct understanding, apply knowledge, solve problems, and conduct inquiry. 
\newthought{Goal Statement:} Upon completion of the General Education curriculum, students integrate critical and creative thinking skills while gaining knowledge of the Arts and Humanities, Mathematics, Natural Sciences, and Social Sciences.

\newthought{Student Outcomes:}

1. Process information by collecting, generating, organizing, retrieving, recognizing underlying assumptions, or validating evidence 
2. Construct understanding by analyzing, synthesizing, revealing meaning, or validating knowledge
3. Apply knowledge by performing, modeling, being creative in a new context, or validating results
4. Solve problems by identifying components, structuring information, anticipating consequences, or creating and improving solutions 
5. Conduct inquiry by formulating research questions, obtaining evidence, explaining knowledge, depicting knowledge, validating or evaluating scholarship


\newpage
\newthought{Required Coursework:}
Students are required to pass 16 credits of critical and creative thinking coursework with at least one course from each list in table three. 

------------------------------------------------------------------------------------------------------------
                                                       Outcomes
List Course                       GERTA      Credits   1           2         3        4       5
---- ---------------------------- --------- --------- ----------- --------- -------- ------ ------- 
A     ART 110:                    HUM        3         +           +          +       +      +
      *Introduction to*
      *the Visual Arts*

A     ART 122:                    FA         3         +           +          +       +      +
      *2-Dimensional*
      *Design*
       
A     ART 130:                    FA         3        +           +          +       +      +
      *Drawing I*

A     ART 250:                    FA         3        +           +          +       +      +
      *Ceramics 1*
      
A     ART 280:                    FA         3        +           +          +       +      +
      *Introduction to*
      *Digital Photography*

A     ENGL 211:                   HUM         3        +          +           +       +       +
      *Introduction to*
      *Creative Writing*

A     COMM 211:                   HUM       3          +            +          +      +     +
      *Oral Interpretation*
      
A     COMM 280:                   HUM        3        +           +          +        +      +
      *Understanding*
      *Film and TV*
      
A     MUSC 100:                   FA         3        +            +           -        -       +
      *Music Appreciation*
      
A     MUSC 102:                   FA         3        ?            ?           ?        ?       ?
      *Popular American*
      *Music*
      
A     MUSC 110:                   FA         3        ?            ?           ?        ?       ?
      *Foundations of*
      *Music*

A     MUSC 140-440A:              FA         3        ?            ?           ?        ?       ?
      *A & B Chorale*

A     MUSC 141-441B:              FA         3        -           -           +         +     -            
      *A & B Concert Band*

A     MUSC 201:                   FA         3        ?            ?           ?        ?       ?
      *World Music*

A     THEA 110:                   FA         3        ?             ?          ?       ?      ?
      *Introduction*
      *to Theather*
      *Arts*

A     THEA 161:                   FA         3        ?             ?          ?       ?      ?
      *Acting I*
    
A     THEA 201-301:               FA         3        +             +          +       +      +
      *Theatre Practicum*



B     ENGL 220:                   HUM         3        +          +           +       +       +
      *Introduction*
      *To Literature*
      
B     ENGL 232:                   HUM        3        +           +          +       +      +
      *Mythology*

B     ENGL 236                    HUM         3       +           +           +       +     +
      *Literature of*
      *Women*
      
B     ENGL 240:                   HUM        3        +           +          +       +      +
      *Masterpieces*
      *of World Literature*
      
B     ENGL 250:                   HUM        3        +           +          +       +      +
      *Masterpieces*
      *of British Literature*
      
B     ENGL 260:                   HUM        3        +           +          +       +      +
      *Masterpieces*
      *of American Literature*
      
B     ENGL 265:                    HUM        3        +           +          +       +      +
      *Native American*
      *Literature*      

C     MATH 103:                    MATH       4        +           +          +       +      +
      *College Algebra*

C     MATH 107:                    MATH       4        +           +          +       +      +
      *Pre-Calculus*

C     MATH 110:                   MATH*       3       ?            ?          ?       ?      ?
      *Liberal Arts*
      *Mathematics*

C     MATH 146:                   MATH        3        ?           ?          ?       ?      ?  
      *Applied*
      *Calculus I*
      
C     MATH 165:                    MATH       4        ?           ?          ?        ?      ?
      *Calculus I*

C     MATH 305:                    MATH       4        +           +          +       +      +
      *Probability &*
      *Statistics*

D     BIOL 111/L:                  LABSC      4        +           +          +       +      +
      *Concepts of*
      *Biology*

D     BIOL 112:                    LABSC*      4        +           +          +       +      +
      *Exploring*
      *Human Health*

D     BIOL 150/L:                  LABSC     4        +           +          +       +      +
      *General*
      *Biology I*      
      
D     BIOL 151/L:                  LABSC*     4        +           +          +       +      +
      *General*
      *Biology II*
      
D     CHEM 115/L:                  LABSC     4        +           +          +       +      +
      *Introductory*
      *Chemistry*

D     CHEM 121/L:                  LABSC     5        +           +          +       +      +
      *General*
      *Chemistry I*
      
D     CHEM 122/L:                  LABSC     5        +           +          +       +      +
      *General*
      *Chemistry II*

D     GEOL 105/L:                  LABSC      4        +           +         +       +       +
      *Physical*
      *Geology*
      

D     GEOL 106/L:                  LABSC*      4        +           +         +       +       +
      *The Earth*
      *Though time*

D     PHYS 110/L:                 LABSC*      4        +           +          +       +      +
      *Introductory*
      *Astronomy*
     
D     PHYS 211/L:                 LABSC      4        +           +          +       +      +
      *College*
      *Physics I*

D     PHYS 212/L:                 LABSC      4        +           +          +       +      +
      *College*
      *Physics II*
     
D     PHYS 251/L:                 LABSC*      4        +           +          +       +      +
      *University*
      *Physics I*

D     PHYS 252/L:                 LABSC*      4        +           +          +       +      +
      *University*
      *Physics II*

D     SCNC 105:                    LABSC      4        +           +          +       +      +
      *Physical*
      *Science*

E     ECON 105:                     SS         3        +           +          +       +      +
      *Elements*
      *of Economics*

E     ECON 106:                     SS         3        +           +          +       -      -
      *Global*
      *Economics*

E     ECON 201:                     SS         3        +           -          +       +      +
      *Principles of*
      *Microeconomics*

E     ECON 202:                    SS*        3        +           +          +       +      +
      *Principles of*
      *Macroeconomics*

E     HIST 103:                   HIST       3        +           +          +       +      +
      *United States*
      *To 1877*

E     HIST 104:                   HIST       3        +           +          +       +      +
      *United States*
      *Since 1877*

E     HIST 211:                   HIST       3        +           +          +       -      -
      *World Civilizations*
      *To 1500*

E     HIST 212:                   HIST       3        +           +          +       +      +
      *World Civilizations*
      *Since 1500*

----------------------------------------------------------------------------------------------------------
Table: Critical and Creative Courses

-----------------------------------------------------

# General Education Electives ^[3 CREDITS REQUIRED]

Students are required to take three additional credits from the General Education curriculum in the areas of Fine Arts, Humanities, Mathematics, Computer Science, Science, or Social Sciences.

\newpage

# APPENDIX

## GERTA Alignment

------------------------------------------------------------------------------------------------------------
                                                          Minimal Credits
General Education Area                                    GERTA    DSU
-------------------------------------------------------- -------- --------- 
Communications                                             9             9         

Arts & Humanities                                          6             6         

Social Sciences                                            6             6         

Mathematics, Science,and Technology                        9            10        

Institution Specific                                       6             6         
                 
Health & Wellness                                          0             2         

**Total**                                                **36**       **39**
-------------------------------------------------------------------------------------------------
Table: Comparison of GERTA and DSU General Education Credit Requirements

------------------------------------------

\newpage

------------------------------------------------------------------------------------------------------
Proficiency     List Course               GERTA      Credits
------------- ------ -------------------- --------- ---------
Citizenship   B      GEOG  121:               SS*       3  
                     *Physical Geology*  
                     
Critical &    C      MATH 110:                MATH*      3
Creative             *Liberal Arts*                 
Thinking             *Mathematics*

Critical &    D      BIOL 112/L:            LABSC*      4
Creative             *Exploring*                 
Thinking             *Human Health*  

Critical &    D      BIOL 151/L:            LABSC*      4
Creative             *General BiOlogy II*                
Thinking     

Critical &    D      GEOL 106/L:             LABSC*      4
Creative             *Earth Through*                 
Thinking             *Time*

Critical &    D      PHYS 110/L:              LABSC*      4
Creative             *Introductory*                 
Thinking             *Astronomy*

Critical &    D      PHYS 212/L:              LABSC*      4
Creative             *College*                 
Thinking             *Physics II*


Critical &    D      PHYS 252/L:              LABSC*      4
Creative             *University*                 
Thinking             *Physics II*

Critical &    E      ECON 202:                 SS*         3
Creative             *Principles of*                 
Thinking             *Macroeconomics*
------------------------------------------------------------------------------------------------------
Table: Courses with not in DSU's GERTA Guide silver pages 


\newpage

## Interstate Passport Alignment

------------------------------------------------------------------------------------------------------------
Foundation Skills                   DSU General Education Category           List(s)                        
----------------------------------- --------------------------------------- -----------
Oral Communications                        Communication                       C

Written Communications                     Communication                       A & B

Quantitative Literacy                     Critical & Creative Thinking         C

-------------------------------------------------------------------------------------------------
Table: Mapping of Interstate Passport foundation-skill blocks to DSU general education learning outcomes

------------------------------------------------------------------------------------------------------------
Knowledge Areas                  DSU General Education Category           List(s)                        
-------------------------------- --------------------------------------- ---------------
Natural Sciences                 Critical & Creative Thinking                D

Human Cultures                   Citizenship                                 B

Human Society                    Citizenship                                 C 

Creative Expression              Critical & Creative Thinking                A

-------------------------------------------------------------------------------------------------
Table: Mapping of Interstate Passport knowledge-area blocks to DSU general education learning outcomes

------------------------------------------------------------------------------------------------------------
Knowledge Areas                  DSU General Education Category           List(s)                        
-------------------------------- --------------------------------------- ---------------
Critical Thinking                Critical & Creative Thinking                All

Teamwork & Values                Communications                              D

-------------------------------------------------------------------------------------------------
Table: Mapping of Interstate Passport crosscutting-skill blocks to DSU General Education learning outcomes


---------------------------------------------------

